# cli.py
# Command-line argument parsing and command dispatch for ek-unique-search-cli
import argparse
import sys
from typing import Optional
from domain import Item
from storage import load_items, save_items
from utils import generate_uuid, sanitize_and_validate_name, parse_tags, NameValidationError
from datetime import datetime


def format_item(item: Item) -> str:
    # Format a single item for stdout
    tags_string = ", ".join(item.tags) if item.tags else "-"
    out = f"ID: {item.id}\n  Name: {item.name}\n  Tags: {tags_string}\n  Created: {item.created_at}"
    return out

def format_items(items) -> str:
    if not items:
        return "No items found."
    return "\n--\n".join(format_item(i) for i in items)

def find_item_by_name(items, name: str) -> Optional[Item]:
    # Exact name match
    target = sanitize_and_validate_name(name)
    for item in items:
        if item.name.lower() == target.lower():
            return item
    return None

def cmd_create(args):
    items = load_items()
    # Determine item name:
    if args.name:
        try:
            name = sanitize_and_validate_name(args.name)
        except NameValidationError as e:
            print(f"Error: {e}")
            sys.exit(1)
        # Enforce uniqueness of name
        if any(it.name.lower() == name.lower() for it in items):
            print(f"Error: Item with name '{name}' already exists.")
            sys.exit(1)
    else:
        # Generate a unique default name like 'item-<shortuuid>'
        short_uuid = generate_uuid().split("-")[0]
        base = f"item-{short_uuid}"
        name = base
        disambig = 0
        while any(it.name.lower() == name.lower() for it in items):
            disambig += 1
            name = f"{base}-{disambig}"
    # Parse tags
    tags = []
    if args.tags:
        try:
            tags = parse_tags(args.tags)
        except Exception as e:
            print(f"Error in tags: {e}")
            sys.exit(1)
    item = Item(id=generate_uuid(), name=name, tags=tags)
    items.append(item)
    try:
        save_items(items)
    except Exception as e:
        print(f"Error: Could not save item: {e}")
        sys.exit(1)
    print("Item created:")
    print(format_item(item))
    sys.exit(0)

def cmd_search(args):
    items = load_items()
    if not items:
        print("No items found.")
        sys.exit(0)
    results = items
    if args.name:
        # Substring (case-insensitive) match
        fragment = args.name.strip().lower()
        results = [it for it in results if fragment in it.name.lower()]
    if args.tag:
        tag = args.tag.strip()
        # Exact tag match
        results = [it for it in results if tag in it.tags]
    if not results:
        print("No items found matching criteria.")
        sys.exit(0)
    print(format_items(results))
    sys.exit(0)

def cmd_list(args):
    items = load_items()
    if not items:
        print("No items found.")
        sys.exit(0)
    print(format_items(items))
    sys.exit(0)

def build_parser():
    parser = argparse.ArgumentParser(
        description="ek-unique-search-cli: Create, search, and list unique items."
    )
    subparsers = parser.add_subparsers(
        dest="command",
        metavar="command [options]",
        required=True,
        help="Subcommand to run (see below)"
    )
    # create
    p_create = subparsers.add_parser(
        "create",
        help="Create a new unique item."
    )
    p_create.add_argument(
        "--name",
        help="Name for the item (unique, optional; if omitted, autogenerated)",
        required=False
    )
    p_create.add_argument(
        "--tags",
        help="Comma-separated list of tags to associate (optional)",
        required=False
    )
    p_create.set_defaults(func=cmd_create)
    # search
    p_search = subparsers.add_parser(
        "search",
        help="Search items by name substring and/or tag."
    )
    p_search.add_argument(
        "--name",
        help="Substring to match in item name (optional)",
        required=False
    )
    p_search.add_argument(
        "--tag",
        help="Exact tag to match (optional)",
        required=False
    )
    p_search.set_defaults(func=cmd_search)
    # list
    p_list = subparsers.add_parser(
        "list",
        help="List all stored items."
    )
    p_list.set_defaults(func=cmd_list)
    return parser

def dispatch(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    if not hasattr(args, 'func'):
        parser.print_help()
        sys.exit(1)
    # Call command handler
    args.func(args)
